import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ProtectedRoutes from "./components/ProtectedRoutes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Cake Management Tool</title>
        <meta name="description" content="Cake Management Tool" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-max`}
      >
        <ProtectedRoutes>
          <Header />
          {children}
          <Footer />
        </ProtectedRoutes>
      </body>
    </html>
  );
}
